"""Seed data for Gullak. All images are curated free Unsplash photos."""

P_IMG = {
    "earring_1": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1400&q=80",
    "earring_2": "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1400&q=80",
    "earring_3": "https://images.unsplash.com/photo-1602748828300-a2a53f77a94f?auto=format&fit=crop&w=1400&q=80",
    "necklace_1": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1400&q=80",
    "necklace_2": "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1400&q=80",
    "bangle_1": "https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=1400&q=80",
    "ring_1": "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1400&q=80",
    "pendant_1": "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1400&q=80",
    "studs_1": "https://images.unsplash.com/photo-1620117654333-c9d7cec4d0a1?auto=format&fit=crop&w=1400&q=80",
    "set_1": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=80",
    "lifestyle_1": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1400&q=80",
    "lifestyle_2": "https://images.unsplash.com/photo-1531995811006-35cb42e1a022?auto=format&fit=crop&w=1400&q=80",
}

COL_IMG = {
    "terracotta": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1600&q=80",
    "wood": "https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1600&q=80",
    "bamboo": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1600&q=80",
    "fabric": "https://images.unsplash.com/photo-1604176354204-9268737828e4?auto=format&fit=crop&w=1600&q=80",
    "wool": "https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1600&q=80",
}

ART_IMG = {
    "kavita": "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=1200&q=80",
    "rajesh": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=1200&q=80",
    "meera": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    "workshop_1": "https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=1400&q=80",
    "workshop_2": "https://images.unsplash.com/photo-1525004482414-ef6d156fde79?auto=format&fit=crop&w=1400&q=80",
}

JOUR_IMG = {
    "heritage": "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=1600&q=80",
    "care": "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=1600&q=80",
    "slow": "https://images.unsplash.com/photo-1583135989598-8bdd0af59cb0?auto=format&fit=crop&w=1600&q=80",
    "styling": "https://images.unsplash.com/photo-1594736797933-d0d3a4a1e40d?auto=format&fit=crop&w=1600&q=80",
    "gift": "https://images.unsplash.com/photo-1608083950849-53f24e59d70e?auto=format&fit=crop&w=1600&q=80",
    "meet": "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1600&q=80",
}

SEED = {
    "collections": [
        {
            "id": "col_terracotta",
            "slug": "terracotta",
            "name": "Terracotta",
            "subtitle": "Earth, shaped by hand.",
            "description": "Our founding collection — jewellery hand-sculpted from natural clay, kiln-fired, and painted in earthen pigments. Each piece carries the quiet imperfections of the maker's hand.",
            "hero_image": COL_IMG["terracotta"],
            "material": "Terracotta",
            "status": "active",
            "order": 1,
        },
        {
            "id": "col_wood", "slug": "wood", "name": "Wood",
            "subtitle": "Grain, warmth, memory.",
            "description": "Sustainably sourced reclaimed woods, carved into wearable heirlooms.",
            "hero_image": COL_IMG["wood"], "material": "Wood", "status": "coming_soon", "order": 2,
        },
        {
            "id": "col_bamboo", "slug": "bamboo", "name": "Bamboo",
            "subtitle": "Feather-light, forest-strong.",
            "description": "Featherlight bamboo pieces designed with quiet minimalism.",
            "hero_image": COL_IMG["bamboo"], "material": "Bamboo", "status": "coming_soon", "order": 3,
        },
        {
            "id": "col_fabric", "slug": "fabric", "name": "Fabric",
            "subtitle": "Threads of tradition.",
            "description": "Handloom cottons and silks folded into soft, sculptural adornment.",
            "hero_image": COL_IMG["fabric"], "material": "Fabric", "status": "coming_soon", "order": 4,
        },
        {
            "id": "col_wool", "slug": "wool", "name": "Wool",
            "subtitle": "Softness, spun.",
            "description": "Handspun natural wool jewellery in undyed, meditative tones.",
            "hero_image": COL_IMG["wool"], "material": "Wool", "status": "coming_soon", "order": 5,
        },
    ],

    "artisans": [
        {
            "id": "art_kavita", "slug": "kavita-devi", "name": "Kavita Devi",
            "craft": "Terracotta sculptor", "region": "Molela, Rajasthan",
            "story": "Kavita learned the language of clay from her grandmother at the age of nine. In her sunlit courtyard, she still shapes each earring by hand — a rhythm passed down through four generations.",
            "portrait": ART_IMG["kavita"],
            "workshop_images": [ART_IMG["workshop_1"], ART_IMG["workshop_2"]],
            "years_of_practice": 22,
        },
        {
            "id": "art_rajesh", "slug": "rajesh-kumhar", "name": "Rajesh Kumhar",
            "craft": "Master kiln-firer", "region": "Khurja, Uttar Pradesh",
            "story": "Rajesh oversees the slow kiln fires that give each Gullak piece its warmth. He watches the flames the way his father did — reading the smoke like a book.",
            "portrait": ART_IMG["rajesh"],
            "workshop_images": [ART_IMG["workshop_2"]],
            "years_of_practice": 28,
        },
        {
            "id": "art_meera", "slug": "meera-bai", "name": "Meera Bai",
            "craft": "Natural pigment painter", "region": "Bhuj, Gujarat",
            "story": "Meera mixes her own earth pigments from ochre, indigo, and river silt. Her brush moves slowly, deliberately — each stroke a small blessing.",
            "portrait": ART_IMG["meera"],
            "workshop_images": [ART_IMG["workshop_1"]],
            "years_of_practice": 15,
        },
    ],

    "products": [
        {
            "id": "prod_saanjh_earrings", "slug": "saanjh-terracotta-earrings",
            "name": "Saanjh Earrings", "subtitle": "Hand-painted terracotta drops",
            "price": 1450.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta, brass hook",
            "story": "Saanjh means dusk — the hour when clay glows like copper. These drops are hand-sculpted, twice-fired, and painted in an ochre wash that shifts with the light.",
            "material_info": "Locally sourced river clay, kiln-fired at 900°C. Ear hooks are nickel-free brass with a matte antique finish.",
            "care_guide": "Wipe gently with a soft dry cloth. Avoid contact with water, perfume, or lotion. Store in the cotton pouch provided.",
            "packaging": "Kraft paper box with a seed paper tag and a handwritten note.",
            "dimensions": "3.2 cm drop", "weight": "6g per pair",
            "images": [P_IMG["earring_1"], P_IMG["earring_2"], P_IMG["earring_3"]],
            "lifestyle_images": [P_IMG["lifestyle_1"]],
            "artisan_id": "art_kavita", "featured": True, "in_stock": True,
        },
        {
            "id": "prod_bhoomi_necklace", "slug": "bhoomi-terracotta-necklace",
            "name": "Bhoomi Necklace", "subtitle": "Layered clay beads on cotton cord",
            "price": 2890.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta beads, natural cotton cord",
            "story": "Bhoomi — the earth. Twenty-one hand-rolled beads, each one a small ritual, strung on undyed cotton with a wooden toggle clasp.",
            "material_info": "Sun-dried, kiln-fired terracotta beads. Cotton cord is unbleached and hand-braided in Bhuj.",
            "care_guide": "Remove before swimming or sleeping. Store flat in a soft pouch. Clay develops a gentle patina with wear.",
            "packaging": "Cotton drawstring pouch inside a recycled kraft box with terracotta wax seal.",
            "dimensions": "46 cm length", "weight": "38g",
            "images": [P_IMG["necklace_1"], P_IMG["necklace_2"]],
            "lifestyle_images": [P_IMG["lifestyle_2"]],
            "artisan_id": "art_kavita", "featured": True, "in_stock": True,
        },
        {
            "id": "prod_aangan_bangle", "slug": "aangan-terracotta-bangle",
            "name": "Aangan Bangle", "subtitle": "Sculpted courtyard bangle",
            "price": 990.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta with matte glaze",
            "story": "Aangan — the courtyard where things happen slowly. A single, sculpted bangle finished in a warm bisque glaze.",
            "material_info": "Solid terracotta, hand-thrown on a slow wheel. Matte bisque finish sealed with beeswax.",
            "care_guide": "Clean with a dry cloth. Do not soak. Store separately to protect the glaze.",
            "packaging": "Recycled kraft sleeve with seed paper tag.",
            "dimensions": "6.5 cm diameter", "weight": "32g",
            "images": [P_IMG["bangle_1"]],
            "lifestyle_images": [],
            "artisan_id": "art_rajesh", "featured": True, "in_stock": True,
        },
        {
            "id": "prod_mitti_ring", "slug": "mitti-terracotta-ring",
            "name": "Mitti Ring", "subtitle": "Single-stone earth ring",
            "price": 780.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta on brass band",
            "story": "Mitti simply means soil — the beginning of everything. A minimal ring featuring a hand-sculpted terracotta cabochon on an adjustable brass band.",
            "material_info": "Nickel-free brass band, hand-polished. Cabochon is polished terracotta with a natural sheen.",
            "care_guide": "Adjust band gently with fingertips. Avoid water and abrasives.",
            "packaging": "Kraft ring box with cotton insert.",
            "dimensions": "Adjustable", "weight": "4g",
            "images": [P_IMG["ring_1"]],
            "lifestyle_images": [],
            "artisan_id": "art_kavita", "featured": False, "in_stock": True,
        },
        {
            "id": "prod_dhoop_pendant", "slug": "dhoop-terracotta-pendant",
            "name": "Dhoop Pendant", "subtitle": "Sunlit terracotta pendant",
            "price": 1690.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta with hand-painted motif",
            "story": "Dhoop — the honeyed light of a winter afternoon. A softly rounded pendant, painted with a single sun motif in ochre and clay.",
            "material_info": "Terracotta pendant on a natural jute cord, closed with a wooden toggle.",
            "care_guide": "Handle painted surface with care. Avoid friction and moisture.",
            "packaging": "Kraft box with cotton pouch and thank-you note.",
            "dimensions": "4 cm pendant, 50 cm cord", "weight": "14g",
            "images": [P_IMG["pendant_1"]],
            "lifestyle_images": [P_IMG["lifestyle_1"]],
            "artisan_id": "art_meera", "featured": True, "in_stock": True,
        },
        {
            "id": "prod_baithak_studs", "slug": "baithak-terracotta-studs",
            "name": "Baithak Studs", "subtitle": "Everyday earthen studs",
            "price": 690.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta with brass posts",
            "story": "Baithak — a quiet sit-down. Small round studs meant to be worn every day, softening with each wear.",
            "material_info": "Hand-rolled clay discs on hypoallergenic brass posts with silicone stoppers.",
            "care_guide": "Remove before showering. Wipe posts occasionally with a soft cloth.",
            "packaging": "Kraft mini box with tissue and stopper card.",
            "dimensions": "0.9 cm disc", "weight": "2g per pair",
            "images": [P_IMG["studs_1"]],
            "lifestyle_images": [],
            "artisan_id": "art_kavita", "featured": False, "in_stock": True,
        },
        {
            "id": "prod_ritu_set", "slug": "ritu-terracotta-set",
            "name": "Ritu Set", "subtitle": "Necklace + earring pairing",
            "price": 3990.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta, cotton, brass",
            "story": "Ritu means season. A curated pairing of a slim terracotta necklace with matching drop earrings — designed for the shift of light between seasons.",
            "material_info": "Necklace on braided cotton cord; earrings on brass hooks. All beads hand-finished.",
            "care_guide": "Store together in the fabric pouch provided. Avoid water and heavy perfume.",
            "packaging": "Two-piece kraft gift box with wax seal and handwritten tag.",
            "dimensions": "Necklace 42cm; earrings 3cm", "weight": "44g total",
            "images": [P_IMG["set_1"], P_IMG["necklace_2"]],
            "lifestyle_images": [P_IMG["lifestyle_2"]],
            "artisan_id": "art_meera", "featured": True, "in_stock": True,
        },
        {
            "id": "prod_chandni_earrings", "slug": "chandni-crescent-earrings",
            "name": "Chandni Earrings", "subtitle": "Crescent-shaped drops",
            "price": 1290.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta with white slip finish",
            "story": "Chandni — moonlight. Slim crescent drops finished in a milky slip, catching light like porcelain.",
            "material_info": "Twice-fired terracotta with a white porcelain slip and brass hooks.",
            "care_guide": "Slip surface is delicate — avoid abrasion. Keep dry.",
            "packaging": "Kraft box with tissue paper and seed tag.",
            "dimensions": "2.8 cm crescent", "weight": "5g per pair",
            "images": [P_IMG["earring_2"], P_IMG["earring_3"]],
            "lifestyle_images": [],
            "artisan_id": "art_meera", "featured": False, "in_stock": True,
        },
        {
            "id": "prod_gulmohar_necklace", "slug": "gulmohar-terracotta-necklace",
            "name": "Gulmohar Necklace", "subtitle": "Blossom-inspired collar",
            "price": 3450.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta petals on cotton",
            "story": "Named after the flame tree that blooms every summer, this collar necklace layers seven hand-shaped clay petals in warm terracotta and rust.",
            "material_info": "Seven kiln-fired petals with a natural sheen, strung on cotton with wooden toggle.",
            "care_guide": "Store flat. Avoid pulling on individual petals.",
            "packaging": "Elongated kraft box with cotton lining.",
            "dimensions": "44 cm length", "weight": "42g",
            "images": [P_IMG["necklace_2"], P_IMG["necklace_1"]],
            "lifestyle_images": [P_IMG["lifestyle_1"]],
            "artisan_id": "art_kavita", "featured": False, "in_stock": True,
        },
        {
            "id": "prod_mausam_bangle_stack", "slug": "mausam-bangle-stack",
            "name": "Mausam Bangle Stack", "subtitle": "Set of three seasonal bangles",
            "price": 2290.0, "currency": "INR",
            "collection_slug": "terracotta", "material": "Terracotta with mixed finishes",
            "story": "Mausam — the passing of seasons. Three slim bangles, each finished differently: matte bisque, ochre wash, and burnt clay.",
            "material_info": "Set of three hand-thrown terracotta bangles.",
            "care_guide": "Stack gently. Store separately when not worn.",
            "packaging": "Three-slot kraft display box.",
            "dimensions": "6.5 cm diameter, 3 bangles", "weight": "92g total",
            "images": [P_IMG["bangle_1"]],
            "lifestyle_images": [],
            "artisan_id": "art_rajesh", "featured": False, "in_stock": True,
        },
    ],

    "journal_posts": [
        {
            "id": "jour_terracotta_heritage", "slug": "the-quiet-heritage-of-terracotta",
            "title": "The Quiet Heritage of Terracotta",
            "subtitle": "An 8000-year-old craft, still practised by hand.",
            "category": "Terracotta Heritage",
            "excerpt": "From the Indus valley to a Rajasthani courtyard, terracotta has been the earth's oldest ornament — hand-shaped and softly imperfect.",
            "body": "Long before gold or silver reached the subcontinent, our ancestors adorned themselves with the earth itself. Terracotta — literally 'baked earth' — is one of the oldest continuous crafts in human history...\n\nIn the villages of Molela and Bhuj, potters still shape jewellery on slow wheels, kiln-fire in wood-heated chambers, and paint with pigments mixed from stone and root. Nothing rushes them. Nothing is ever quite the same twice.\n\nAt Gullak, we treat these imperfections not as flaws, but as the fingerprints of the maker. The tiny groove where a thumb pressed too firmly. The uneven blush left by a slow kiln. A piece of the maker, in every piece.",
            "cover_image": JOUR_IMG["heritage"], "author": "Gullak Studio", "read_time": "6 min read", "published": True,
        },
        {
            "id": "jour_care", "slug": "how-to-care-for-clay-jewellery",
            "title": "How to Care for Clay Jewellery",
            "subtitle": "Small rituals for a piece that will last a lifetime.",
            "category": "Jewellery Care",
            "excerpt": "Terracotta is quietly durable — but like all natural materials, it responds to how you treat it.",
            "body": "A well-cared-for clay piece can travel with you for years, softening gently with wear...\n\n1. Keep it dry. Water and clay are the beginning of everything, and also the end. Wipe with a soft cloth after wear.\n2. Store it separately. Cotton pouches, provided with every Gullak order, are ideal.\n3. Let it patina. Small marks and warmth are the piece becoming yours.",
            "cover_image": JOUR_IMG["care"], "author": "Gullak Studio", "read_time": "3 min read", "published": True,
        },
        {
            "id": "jour_slow", "slug": "a-case-for-slow-fashion",
            "title": "A Case for Slow Fashion",
            "subtitle": "Why the future of style is quieter, not louder.",
            "category": "Slow Fashion",
            "excerpt": "The most radical thing you can wear right now is a piece with a story you can trace.",
            "body": "Slow fashion isn't a trend. It's the return of an older idea — that the things we wear are extensions of the people who made them...\n\nAt Gullak, we speak first names. Kavita made this pair of earrings. Rajesh watched them fire. Meera painted them. When you wear a Gullak piece, you are wearing a small quiet community.",
            "cover_image": JOUR_IMG["slow"], "author": "Gullak Studio", "read_time": "5 min read", "published": True,
        },
        {
            "id": "jour_meet", "slug": "meet-kavita-devi",
            "title": "Meet Kavita Devi",
            "subtitle": "The hands behind the Saanjh earrings.",
            "category": "Meet the Artisan",
            "excerpt": "A morning with Kavita in her sunlit Molela courtyard, four generations of clay memory beneath her hands.",
            "body": "Kavita's grandmother taught her the shape of a pot at nine years old...\n\nToday, she works from the same courtyard, now with her own daughter watching. She still uses river clay her son brings home in a jute sack. She still hums the same songs while she works.",
            "cover_image": JOUR_IMG["meet"], "author": "Gullak Studio", "read_time": "7 min read", "published": True,
        },
        {
            "id": "jour_styling", "slug": "three-ways-to-style-terracotta",
            "title": "Three Ways to Style Terracotta",
            "subtitle": "With linen, with khadi, with your favourite ivory silk.",
            "category": "Styling Guides",
            "excerpt": "Earthen jewellery is more versatile than you'd think — the trick is in the fabric.",
            "body": "Terracotta loves natural fibres...\n\n— With linen: pair a slim necklace with an oversized shirt and rolled sleeves.\n— With khadi: let a pair of studs sit against a soft-collared kurta.\n— With ivory silk: a single bangle is enough. Trust the material.",
            "cover_image": JOUR_IMG["styling"], "author": "Gullak Studio", "read_time": "4 min read", "published": True,
        },
    ],

    "testimonials": [
        {"id": "t1", "author": "Ananya R.", "location": "Bengaluru", "quote": "I've never owned a piece of jewellery that felt this personal. My Saanjh earrings have become my daily companion.", "product_name": "Saanjh Earrings"},
        {"id": "t2", "author": "Priya M.", "location": "Mumbai", "quote": "The unboxing alone made me cry. A handwritten note, a seed paper tag, and the warmest terracotta beads I've ever held.", "product_name": "Bhoomi Necklace"},
        {"id": "t3", "author": "Ritu S.", "location": "Jaipur", "quote": "This is what luxury should feel like — quiet, handmade, and full of story.", "product_name": "Ritu Set"},
        {"id": "t4", "author": "Meher K.", "location": "Delhi", "quote": "I love how each earring is slightly different. Nothing feels mass-produced. Everything feels loved.", "product_name": "Chandni Earrings"},
        {"id": "t5", "author": "Sara J.", "location": "Kolkata", "quote": "Gullak has changed how I think about jewellery. Fewer pieces. More meaning.", "product_name": "Aangan Bangle"},
        {"id": "t6", "author": "Ishani P.", "location": "Pune", "quote": "The story of the artisan on the tag made me pause. It's rare to buy something and know exactly who made it.", "product_name": "Mitti Ring"},
    ],
}
