export const TID = {
  header: {
    root: "site-header",
    logo: "header-logo-link",
    navShop: "header-nav-shop",
    navJournal: "header-nav-journal",
    navAbout: "header-nav-about",
    navCraft: "header-nav-craftsmanship",
    navArtisans: "header-nav-artisans",
    wishlist: "header-wishlist-button",
    cart: "header-cart-button",
    account: "header-account-button",
    mobileMenu: "header-mobile-menu-button",
  },
  home: {
    heroCta: "home-hero-shop-cta",
    heroStoryCta: "home-hero-story-cta",
    newsletter: "home-newsletter-form",
    newsletterInput: "home-newsletter-input",
    newsletterSubmit: "home-newsletter-submit",
    featuredGrid: "home-featured-products-grid",
    collectionsGrid: "home-collections-grid",
  },
  productCard: {
    root: "product-card",
    open: "product-card-open-link",
    price: "product-card-price",
    wishlist: "product-card-wishlist-button",
  },
  pdp: {
    price: "pdp-price",
    addToCart: "pdp-add-to-cart-button",
    wishlist: "pdp-wishlist-button",
    gallery: "pdp-image-gallery",
    thumb: "pdp-image-thumb",
  },
  collections: {
    grid: "collections-product-grid",
    sortSelect: "collections-sort-select",
  },
  cart: {
    drawer: "cart-drawer",
    open: "cart-open-drawer-button",
    checkout: "cart-drawer-checkout-button",
    remove: "cart-drawer-remove-item-button",
    empty: "cart-empty-state",
  },
  checkout: {
    form: "checkout-address-form",
    place: "checkout-place-order-button",
    summary: "checkout-order-summary",
  },
  auth: {
    googleBtn: "login-google-button",
    logout: "account-logout-button",
  },
  admin: {
    loginForm: "admin-login-form",
    loginEmail: "admin-login-email",
    loginPassword: "admin-login-password",
    loginSubmit: "admin-login-submit",
    nav: "admin-sidebar",
    productsTable: "admin-products-table",
    createProduct: "admin-create-product-button",
  },
};
